### ISSUE TITLE
[Warlock]Grimoire of Supremacy

### ISSUE THREAD

**Issue by Tudi** [FeenixServerProject/Pandaria_5.4.2_Issue_tracker#1] opened 2015-04-07 18:38 UTC
causes all warlock pets to only auto-attack

got it from forcy

**Comment by ghost** [comment] 2015-08-20 11:26
Unable to reproduce issue. Require more information from testing.

**Comment by Zerixx** [comment] 2015-10-06 16:28
Fixed in 5.4.8.

**Closed as completed by Zerixx** 2015-10-06 16:28 UTC
Labels: Class.Spells
